export const CAMPUSES: string[] = [
  "Acadia University - Wolfville",
  "Algonquin College - Ottawa",
  "Algonquin College - Pembroke",
  "Algonquin College - Perth",
  "Ambrose University",
  "Athabasca University",
  "Bishop's University",
  "Brandon University",
  "Bridges - Brampton",
  "Bridges - Carleton University",
  "Bridges - London",
  "Bridges - Sheridan Davis",
  "Bridges - University of British Columbia",
  "Bridges - University of Calgary",
  "Bridges - University of Guelph",
  "Bridges - University of Ottawa",
  "Bridges - University of Saskatchewan",
  "Bridges - University of Toronto",
  "Bridges - York University",
  "Briercrest College and Seminary",
  "British Columbia Institute of Technology",
  "Brock University",
  "Camosun College",
  "Campus Notre-Dame-de-Foy",
  "Canada Christian College",
  "Canadian Mennonite University",
  "Canadore College",
  "Capernwray Harbor Bible Centre",
  "Capilano University",
  "Capilano University - Squamish",
  "Carleton University",
  "Cégep Ahuntsic",
  "Cégep André-Laurendeau",
  "Cégep de Chicoutimi",
  "Cégep de Granby",
  "Cégep de Jonquière",
  "Cégep de l'Outaouais",
  "Cégep de Lanaudière",
  "Cégep de Saint-Jean-sur-Richelieu",
  "Cégep de Sainte-Foy",
  "Cégep de Sherbrooke",
  "Cégep De Thetford",
  "Cégep de Trois-Rivières",
  "Cégep Édouard-Montpetit",
  "Cégep Garneau",
  "Cégep Limoilou",
  "Cégep Sorel-Tracy",
  "Centennial College",
  "Champlain College - St-Lambert",
  "Champlain College - St-Lawrence",
  "Collège Boréal",
  "Collège communautaire du Nouveau-Brunswick - Bathurst",
  "Collège communautaire du Nouveau-Brunswick - Campbellton",
  "Collège communautaire du Nouveau-Brunswick - Dieppe",
  "Collège communautaire du Nouveau-Brunswick - Edmundston",
  "Collège communautaire du Nouveau-Brunswick - Péninsule acadienne",
  "Collège de l'Île",
  "Collège François-Xavier-Garneau",
  "Collège La Cité - Alphonse-Desjardins",
  "Collège La Cité - Hawkesbury",
  "Collège La Cité - Ottawa",
  "Collège La Cité - Toronto",
  "Collège Mathieu",
  "Collège Montmorency",
  "College of New Caledonia",
  "College of the Rockies",
  "Collège Universel - Gatineau",
  "Columbia Bible College",
  "Concordia University",
  "Conestoga College - Brantford",
  "Conestoga College - Cambridge",
  "Conestoga College - Doon",
  "Conestoga College - Waterloo",
  "Confederation College",
  "Crandall University",
  "Dalhousie University",
  "Dawson College",
  "Douglas College - Coquitlam",
  "Douglas College - New Westminster",
  "Durham College",
  "École de musique Vincent-d'Indy",
  "Emily Carr University of Art + Design",
  "ÉMOICQ",
  "Faculté de Théologie Scriptura",
  "Fanshawe College",
  "George Brown College",
  "Georgian College - Barrie",
  "Georgian College - Orillia",
  "Halifax",
  "HEC Montréal",
  "Heritage College and Seminary",
  "Horizon College and Seminary",
  "HOWM",
  "Humber College",
  "ITAQ",
  "John Abbott College",
  "Kingswood University",
  "Kwantlen Polytechnic University - Richmond",
  "Kwantlen Polytechnic University - Surrey",
  "La Cité universitaire francophone",
  "Lakehead University - Orillia",
  "Lakehead University - Thunder Bay",
  "Lakeland College",
  "Langara College",
  "Laurentian University",
  "Lethbridge Polytechnic",
  "Louis Riel Arts and Technology Centre",
  "MacEwan University",
  "Manitoba Institute of Trades and Technology",
  "Marianopolis College",
  "Master's College and Seminary",
  "McGill University",
  "McGill University - Macdonald",
  "McMaster Divinity College",
  "McMaster University",
  "Medicine Hat College",
  "Memorial University of Newfoundland",
  "Millar College of the Bible",
  "Mohawk College",
  "Mount Royal University",
  "Mount Saint Vincent University",
  "New Brunswick Community College",
  "NEXT",
  "Niagara College",
  "Nipissing University",
  "Norquest College",
  "Northern Lakes College",
  "Northern Lights College",
  "Northwest College and Seminary",
  "Northwestern Polytechnic",
  "Nova Scotia Community College",
  "NSCAD University",
  "Okanagan College - Kelowna",
  "Okanagan College - Penticton",
  "Okanagan College - Vernon",
  "Olds College",
  "Ontario Institute of Audio Recording Technology",
  "Ontario Tech University",
  "Ottawa",
  "Oulton College - Elmwood Drive",
  "Oulton College - Flanders Court",
  "Oulton College - Pacific Avenue",
  "Pacific Life Bible College",
  "Parole de Vie Québec",
  "Polytechnique de Montréal",
  "Prairie College",
  "Providence University College",
  "Queen's University",
  "Red Deer Polytechnic",
  "Red River College",
  "Redeemer University",
  "Royal Military College",
  "Saint Mary's University",
  "Saskatchewan Polytechnic - Prince Albert",
  "Saskatchewan Polytechnic - Regina",
  "Saskatchewan Polytechnic - Saskatoon",
  "Saskatoon Business College",
  "Seneca Polytechnic - Newnham",
  "Sheridan College - Davis",
  "Sheridan College - Mississauga",
  "Sheridan College - Oakville",
  "Simon Fraser University",
  "Southern Alberta Institute of Technology",
  "St. Clair College",
  "St. Francis Xavier University",
  "St. Lawrence College",
  "St. Thomas University",
  "Steinbach Bible College",
  "Summit Pacific College",
  "The King's University",
  "Thompson Rivers University",
  "Toronto Metropolitan University",
  "Trent University",
  "Trinity Western University",
  "Tyndale University",
  "Université de Hearst",
  "Université de Hearst - Kapuskasing",
  "Université de Hearst - Timmins",
  "Université de l'Ontario français",
  "Université de Moncton",
  "Université de Montréal",
  "Université de Saint-Boniface",
  "Université de Sherbrooke",
  "Université du Québec à Chicoutimi",
  "Université du Québec à Rimouski",
  "Université du Québec en Outaouais",
  "Université Laval",
  "Université Sainte-Anne",
  "Université TÉLUQ",
  "University Canada West",
  "University of Alberta",
  "University of Alberta - Saint-Jean",
  "University of British Columbia",
  "University of British Columbia - Okanagan",
  "University of Calgary",
  "University of Guelph",
  "University of Guelph - Humber",
  "University of King's College",
  "University of Lethbridge",
  "University of Manitoba",
  "University of New Brunswick",
  "University of Ottawa",
  "University of Prince Edward Island",
  "University of Regina",
  "University of Saskatchewan",
  "University of the Fraser Valley",
  "University of Toronto - Mississauga",
  "University of Toronto - Scarborough",
  "University of Toronto - St. George",
  "University of Victoria",
  "University of Waterloo",
  "University of Windsor",
  "University of Winnipeg",
  "UQÀM",
  "UQTR",
  "Vancouver Island University",
  "Vanguard College",
  "Vanier College",
  "Western University",
  "Wilfrid Laurier University",
  "Wilfrid Laurier University - Brantford",
  "York University",
  "York University - Glendon",
  "Other",
];

